contract/urls.py
from django.conf.urls import url
from django.urls import path
from . import views


urlpatterns = [
    url(r'^$', views.ContractList, name='contract-list'),
    
    # path('contract/create', views.contract_create, name='contract_create'),
    path('contract/manage', views.contract_create, name='contract_create'),

    # path('contract/<int:pk>/update', views.ContractUpdate, name='contract-update'),
    # url(r'^ajax/update_contract/$', views.UpdateContract, name='update-contract'),
    url(r'^ajax/create_contract/$', views.CreateContract, name='create-contract'),
    
    url(r'^ajax/get_wagerate_list/$', views.get_wagerate_list, name='get_wagerate_list'),
    
    url(r'^ajax/get_contract_list/$', views.get_contract_list, name='get_contract_list'),
    url(r'^ajax/get_contract_list_modal/$', views.get_contract_list_modal, name='get_contract_list_modal'),

    url(r'^ajax/get_wagerate_list_modal/$', views.get_wagerate_list_modal, name='get_wagerate_list_modal'),    

    url(r'^ajax/update_customer_service/$', views.update_customer_service, name='update_customer_service'),
    url(r'^ajax/save_new_service/$', views.save_new_service, name='save_new_service'),
    url(r'^ajax/add_new_service/$', views.add_new_service, name='add_new_service'),
    url(r'^ajax/save_customer_service_item/$', views.save_customer_service_item, name='save_customer_service_item'),
    url(r'^ajax/get_cus_main/$', views.get_cus_main, name='get_cus_main'),
    url(r'^ajax/get_customer/$', views.get_customer, name='get_customer'),
    url(r'^ajax/get_cus_contract/$', views.get_cus_contract, name='get_cus_contract'),
    url(r'^ajax/get_rank_shift_list/$', views.get_rank_shift_list, name='get_rank_shift_list'),
    url(r'^ajax/reload_service_list/$', views.reload_service_list, name='reload_service_list'),
    url(r'^ajax/reload_contract_list/$', views.reload_contract_list, name='reload_contract_list'),
    url(r'^ajax/delete_customer_service/$', views.delete_customer_service, name='delete_customer_service'),
    url(r'^ajax/delete_customer_contract/$', views.delete_customer_contract, name='delete_customer_contract'),
    
    # url(r'^generate-contract/(?P<cnt_id>\d+)/$', views.generate_contract, name='generate_contract'),
    # url(r'^generate-contract/(?P<cnt_id>\d+)/(?P<language_option>\w+)/$', views.generate_contract, name='generate-contract'),
    url(r'^generate-contract/(?P<cnt_id>\d+)/(?P<language_option>\w+)/(?P<is_new_report>\w+)/(?P<is_amendment>\w+)/(?P<is_customer_address>\w+)/$', views.generate_contract, name='generate-contract'),
    url(r'^download-contract/(?P<cnt_id>\d+)/(?P<language_option>\w+)/(?P<is_new_report>\w+)/(?P<is_amendment>\w+)/(?P<is_customer_address>\w+)/$', views.download_contract, name='download-contract'),
    #url(r'^download-contract/(?P<file_name>[-\w_\\-\\.]+)$', views.download_contract, name='download-contract'),
    url(r'^print-contract/(?P<file_name>[-\w_\\-\\.]+)$', views.print_contract, name='print-contract'),
    url(r'^ajax/ajax_undelete_contract/$', views.ajax_undelete_contract, name='ajax_undelete_contract'),

    url(r'^ajax/sp_adjust_new_price/$', views.ajax_sp_adjust_new_price, name='ajax_sp_adjust_new_price'),
]

contract/forms.py
from django import forms
from .models import CusContract
from customer.models import Customer
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
import datetime


class ContractForm(forms.ModelForm):
    print("debug ContractForm")
    cus_id = forms.DecimalField(label='Customer ID', required=False, max_value=9999999)
    cus_brn = forms.DecimalField(label='Branch', required=False, max_value=999, min_value=0)
    cus_vol = forms.DecimalField(label='Volume', required=False, max_value=999, min_value=0)

    class Meta:
        model = CusContract
        fields = ['cus_brn', 'cus_vol', 'cus_id'] 

    def __init__(self, *args, **kwargs):    	
        super(ContractForm, self).__init__(*args, **kwargs)

        self.fields['cus_id'].widget.attrs = {'class': 'form-control form-control-md', 'placeholder': _('Customer ID')}        
        self.fields['cus_id'].error_messages = {'required': _('กรุณาป้อนข้อมูล'), 'max_value': _('รหัสสัญญาเกิน 7 หลัก')}

        self.fields['cus_brn'].widget.attrs={'class': 'form-control form-control-md', 'placeholder': _('Branch')}
        self.fields['cus_brn']._messages = {'required': _('กรุณาป้อนข้อมูล'), 'max_value': _('รหัสสาขาเกิน 3 หลัก'), 'min_value': _('ป้อนข้อมูลน้อยกว่า 0')}

        # self.fields['cus_vol'].widget.attrs={'class': 'form-control form-control-sm', 'placeholder': _('Volume')}
        # self.fields['cus_vol'].error_messages = {'required': _('กรุณาป้อนข้อมูล'), 'max_value': _('รหัสลำดับสัญญาเกิน 3 หลัก'), 'min_value': _('ป้อนข้อมูลน้อยกว่า 0')}

    def clean_cus_id(self):
        if self.instance:
            return self.instance.cus_id
        else: 
            return self.fields['cus_id']
        
    def clean_cus_brn(self):
        if self.instance: 
            return self.instance.cus_brn
        else: 
            return self.fields['cus_brn']

    def clean_cus_vol(self):
        if self.instance: 
            return self.instance.cus_vol
        else: 
            return self.fields['cus_vol']


class ContractUpdateForm(forms.ModelForm):
    cnt_active = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    cnt_doc_no = forms.CharField(required=False)
    cnt_apr_by_id = forms.CharField(required=False)
    cnt_doc_date = forms.DateField(required=True, widget=forms.DateInput(format='%d/%m/%Y'), input_formats=('%d/%m/%Y', ))
    cnt_eff_frm = forms.DateField(required=False, widget=forms.DateInput(format='%d/%m/%Y'), input_formats=('%d/%m/%Y', ))
    cnt_eff_to = forms.DateField(required=False, widget=forms.DateInput(format='%d/%m/%Y'), input_formats=('%d/%m/%Y', ))
    cnt_sign_frm = forms.DateField(required=False, widget=forms.DateInput(format='%d/%m/%Y'), input_formats=('%d/%m/%Y', ))
    cnt_sign_to = forms.DateField(required=False, widget=forms.DateInput(format='%d/%m/%Y'), input_formats=('%d/%m/%Y', ))

    class Meta:
        model = CusContract  
        fields = '__all__'
        exclude = ['cnt_id', 'cus_brn', 'cus_vol']

    def __init__(self, *args, **kwargs):
        super(ContractUpdateForm, self).__init__(*args, **kwargs)        
        instance = getattr(self, 'instance', None)        
        self.fields['cnt_doc_no'].error_messages = {'required': _('<b>Contract Ref.</b> is required.')}
        self.fields['cnt_doc_date'].error_messages = {'required': _('<b>Contract Date</b> is required.')}
                
        self.fields['cnt_doc_date'].widget.attrs.update({'class': 'form-control form-control-sm', 'id': 'id_cnt_doc_date', 'placeholder': _('')})
        self.fields['cnt_eff_frm'].widget.attrs.update({'class': 'form-control form-control-sm', 'id': 'id_cnt_eff_frm', 'placeholder': _('dd/mm/yyyy')})
        self.fields['cnt_eff_to'].widget.attrs.update({'class': 'form-control form-control-sm', 'id': 'id_cnt_eff_to', 'placeholder': _('dd/mm/yyyy')})
        self.fields['cnt_sign_frm'].widget.attrs.update({'class': 'form-control form-control-sm', 'id': 'id_cnt_sign_frm', 'placeholder': _('dd/mm/yyyy')})
        self.fields['cnt_sign_to'].widget.attrs.update({'class': 'form-control form-control-sm', 'id': 'id_cnt_sign_to', 'placeholder': _('dd/mm/yyyy')})
        
    def clean_cnt_doc_no(self):
        data = self.data.get('cnt_doc_no')
        if len(data) == '0':
            raise ValidationError("Contrct Ref. is required.")
        return data


class ContractCreateForm(forms.ModelForm):
    cnt_id = forms.DecimalField(label='Contract ID', required=False)
    cus_id = forms.DecimalField(label='Customer ID', required=False)
    cus_brn = forms.DecimalField(label='Customer Branch', required=False)
    cus_vol = forms.DecimalField(label='Customer Volume', required=False)
    cnt_apr_by_text = forms.CharField(required=False)

    # Date format
    cnt_doc_date = forms.DateField(required=True, widget=forms.DateInput(format='%d/%m/%Y'), input_formats=('%d/%m/%Y', ))
    cnt_eff_frm = forms.DateField(required=True, widget=forms.DateInput(format='%d/%m/%Y'), input_formats=('%d/%m/%Y', ))
    cnt_eff_to = forms.DateField(required=True, widget=forms.DateInput(format='%d/%m/%Y'), input_formats=('%d/%m/%Y', ))
    cnt_sign_frm = forms.DateField(required=True, widget=forms.DateInput(format='%d/%m/%Y'), input_formats=('%d/%m/%Y', ))
    cnt_sign_to = forms.DateField(required=True, widget=forms.DateInput(format='%d/%m/%Y'), input_formats=('%d/%m/%Y', ))

    cnt_guard_amt = forms.DecimalField(required=False, min_value=0)
    cnt_sale_amt = forms.DecimalField(required=False, min_value=0)

    class Meta:
        model = CusContract  
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(ContractCreateForm, self).__init__(*args, **kwargs)        
        instance = getattr(self, 'instance', None)                        
        self.fields['cus_id'].widget.attrs.update({'class': 'form-control form-control-md col-3', 'placeholder': _(''), 'autocomplete':'off'})
        self.fields['cus_brn'].widget.attrs.update({'class': 'form-control form-control-md col-2', 'placeholder': _(''), 'autocomplete':'off'})
        self.fields['cus_vol'].widget.attrs.update({'class': 'form-control form-control-md col-2', 'placeholder': _(''), 'autocomplete':'off'})

        self.fields['cnt_doc_date'].widget.attrs.update({'class': 'form-control form-control-sm', 'id': 'id_cnt_doc_date', 'placeholder': _('dd/mm/yyyy')})
        self.fields['cnt_eff_frm'].widget.attrs.update({'class': 'form-control form-control-sm', 'id': 'id_cnt_eff_frm', 'placeholder': _('dd/mm/yyyy')})
        self.fields['cnt_eff_to'].widget.attrs.update({'class': 'form-control form-control-sm', 'id': 'id_cnt_eff_to', 'placeholder': _('dd/mm/yyyy')})
        self.fields['cnt_sign_frm'].widget.attrs.update({'class': 'form-control form-control-sm', 'id': 'id_cnt_sign_frm', 'placeholder': _('dd/mm/yyyy')})
        self.fields['cnt_sign_to'].widget.attrs.update({'class': 'form-control form-control-sm', 'id': 'id_cnt_sign_to', 'placeholder': _('dd/mm/yyyy')})
        self.fields['cnt_apr_by_text'].widget.attrs.update({'class': 'form-control form-control-sm', 'id': 'id_cnt_apr_by_text'})
        self.fields['cnt_guard_amt'].widget.attrs.update({'class': 'form-control form-control-sm text-right', 'id': 'id_cnt_guard_amt'})
        self.fields['cnt_sale_amt'].widget.attrs.update({'class': 'form-control form-control-sm text-right', 'id': 'id_cnt_sale_amt'})
        self.fields['cnt_guard_amt'].widget.attrs['readonly'] = True
        self.fields['cnt_sale_amt'].widget.attrs['readonly'] = True
        self.fields['cnt_apr_by_text'].widget.attrs['readonly'] = True

        # Initial value
        self.fields['cnt_doc_date'].initial = datetime.date.today
        self.fields['cnt_eff_frm'].initial = datetime.date.today
        self.fields['cnt_eff_to'].initial = datetime.datetime.strptime("31/12/2999", "%d/%m/%Y").date()
        self.fields['cnt_sign_frm'].initial = datetime.date.today
        self.fields['cnt_sign_to'].initial = datetime.datetime.strptime("31/12/2999", "%d/%m/%Y").date()
        self.fields['cnt_apr_by_text'].initial = "ดร.ชนัต สุขสุวรรณธร (Dr.Chanat Suksuwannatorn)"
        self.fields['cnt_guard_amt'].initial = 0
        self.fields['cnt_sale_amt'].initial = 0

contract/templates/contract/contract_form.html
{% extends "page_generic.html" %}

{% load i18n %}
{% block title %} {{ page_title}} - {% trans 'Contract List' %} {% endblock %}
{% load static %}
{% load widget_tweaks %}

{% block content %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">{% trans 'Contract List' %}</h1>
          </div>
          <div class="col-sm-6">
            <!--
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="/">Home</a></li>
              <li class="breadcrumb-item active">Contract</li>
            </ol>
            -->
          </div>
        </div>
      </div>
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="card">

        <div class="col-sm-8 offset-sm-2 col-md-8 offset-md-2 pt-4 pl-4 pr-4"> 

          <form class="form-row" method="post" autocomplete="off">
            {% csrf_token %}
            <div class="form-row">

              <div class="col-3">
                {% if form.cus_id.errors %}                
                  {% render_field form.cus_id class="form-control form-control-sm is-invalid" %}                
                  {% for error in form.cus_id.errors %}
                  <div class="invalid-feedback">
                    {{error}}
                  </div>
                  {% endfor %}
                {% else %}
                  {% render_field form.cus_id class="form-control form-control-sm" %}
                {% endif %}
              </div>

              <div class="col-3">
                {% if form.cus_brn.errors %}                
                  {% render_field form.cus_brn class="form-control form-control-sm is-invalid" %}
                  {% for error in form.cus_brn.errors %}
                  <div class="invalid-feedback">
                    {{error}}
                  </div>
                  {% endfor %}                
                {% else %}
                  {% render_field form.cus_brn class="form-control form-control-sm" %}
                {% endif %}              
              </div>

              <div class="col-3">
                {% if form.cus_vol.errors %}                
                  {% render_field form.cus_vol class="form-control form-control-sm is-invalid" %}
                  {% for error in form.cus_vol.errors %}
                  <div class="invalid-feedback">
                    {{error}}
                  </div>
                  {% endfor %}                
                {% else %}
                  {% render_field form.cus_vol class="form-control form-control-sm" %}
                {% endif %}              
              </div>

              <div colass="col-2">
                <button type="submit" class="btn btn-sm btn-primary col-xs-2"><i class="fas fa-search fa-sm"></i>&nbsp;{% trans 'Search' %}</button>
                <!--<button type="reset" class="btn btn-sm btn-outline-secondary col-xs-2">{% trans 'Clear' %}</button>-->
              </div>

            </div>
          </form>

        </div>

        {% if form.errors %}
        <div class="col-md-6 offset-md-3 pt-2 pl-15">
          <div class="container-fluid" id="show-error">       
            <!--
            {% for field in form %}
                {% for error in field.errors %}
                    <div class="alert alert-danger">
                        <strong><i class="fas fa-exclamation"></i>&nbsp;&nbsp;{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endfor %}
            -->

            <!--
            {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                    <i class="fas fa-exclamation"></i>&nbsp;&nbsp;{{ error|escape }}
                </div>
            {% endfor %}
            -->
          </div>        
        </div>
        {% endif %}

        <div class="card-header" style="vertical-align: middle;">
          <div class="card-tools">
            <!--
            <button type="button" class="btn btn-success btn-sm js-create-customer" data-url="{% url 'customer-create' %}"><i class="fas fa-plus"></i>&nbsp;&nbsp;{% trans 'Add' %}</button>
            -->          
            <!--
            <div class="float-right"><a href="{% url 'customer-create' %}" type="button" class="btn btn-success btn-sm float-right"><i class="fas fa-plus fa-xs"></i>&nbsp;&nbsp;{% trans 'Add' %}</a></div>-->          
          </div>
        </div>
        
        <div class="card-body">
          
          <div class="float-right pb-3"><a href="{% url 'customer-create' %}" type="button" class="btn btn-success btn-sm"><i class="fas fa-plus fa-xs"></i>&nbsp;&nbsp;{% trans 'New' %}</a></div>

          {% if current_page %}
            <table id="customer-list-table1" class="table table-bordered table-striped table-sm">
              <thead>
              <tr>
                <th scope="col">{% trans 'Contract ID' %}</th>
                <th scope="col">{% trans 'Customer Name (TH)' %}</th>
                <th scope="col">{% trans 'Customer Name (EN)' %}</th>            
              </tr>
              </thead>
              <tbody>
                {% include 'customer/partial_customer_list.html' %}
              </tbody>
            </table>

            {% if is_paginated %}
            <div>
                <span>
                    {% if current_page.has_previous %}
                        <a href="?page={{current_page.previous_page_number}}&cusname={{cus_name|default:''}}&cusid={{cus_id|default:'' }}&cusbrn={{cus_brn|default:''}}"><i class="fas fa-arrow-circle-left"></i></a>
                    {% endif %}
                    &nbsp;
                    <span>
                        {% trans 'Page' %} {{ current_page.number }} {% trans '/' %} {{ current_page.paginator.num_pages }}
                    </span>
                    &nbsp;
                    {% if current_page.has_next %}
                        <a href="?page={{ current_page.next_page_number }}&cusname={{cus_name|default:''}}&cusid={{cus_id|default:'' }}&cusbrn={{cus_brn|default:'' }}"><i class="fas fa-arrow-circle-right"></i></a>
                    {% endif %}
                </span>
            </div>
            {% endif %}
          
          {% else %}
          <div class="table-responsive">
            <table class="table table-bordered text-secondary table-striped table-sm table-condensed">
              <thead>
              <tr>
                <th scope="col">{% trans 'Contract ID' %}</th>
                <th scope="col">{% trans 'Customer Name (TH)' %}</th>
                <th scope="col">{% trans 'Customer Name (EN)' %}</th>            
              </tr>
              </thead>
              <tbody>            
                <tr class="bg-warning">
                  <td colspan="5" align="center"><br>{% trans 'There is no data displayed.' %}<br><br></td>
                </tr>
              </tbody>
            </table>
          </div>
          {% endif %}
       
        </div>
        <!-- /.card-body -->

        <!--
        <div class="card-footer">
          &nbsp;
        </div>
        -->

        <!-- /.card-footer-->

    </div>
    <!-- /.card -->

    <div class="modal fade" id="modal-customer">
      <div class="modal-dialog">
        <div class="modal-content"></div>
      </div>
    </div>


    </section>
    <!-- /.content -->





  </div>

{% endblock %}


{% block scripts %}
<script>

  $(document).on('click', '#vert-tabs-contract-en-tab', function(event) {
    cus_name_en = jQuery('#customer_name_en').val();
    $(".card-title").html(cus_name_en);

  });

  $(document).on('click', '#vert-tabs-contract-th-tab', function(event) {
    cus_name_th = jQuery('#customer_name_th').val();
    $(".card-title").html(cus_name_th);

  });

  $('#id_cus_id').focus();

  $('#id_cus_id').on('keypress', function (e) {
    if(e.which === 13){
      $('#id_cus_brn').focus();
      event.preventDefault();
      return false;        
    }
  });

  $('#id_cus_brn').on('keypress', function (e) {
    if(e.which === 13){
      $('#id_cus_vol').focus();
      event.preventDefault();
      return false;        
    }
  });

  /*
  $('#id_cus_vol').on('keypress', function (e) {
    if(e.which === 13){      
      event.preventDefault();
      $('#contract-form').submit();
      return false;    
    }
  });
  */

  $("#contract-form").submit(function(e) {
    e.preventDefault();

    var data = $(this).serialize();
    $.ajax({
          type:'POST',
          url:'{% url "contract_create" %}',
          data:{
              cus_id:$('#id_cus_id').val(),
              cus_brn:$('#id_cus_brn').val(),
              cus_vol:$('#id_cus_vol').val(),
              csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
              action: 'post'
          },
          beforeSend: function(){
            $('#waitingDialog').modal();          
          },
          complete: function(){
            $('#waitingDialog').modal('hide');
          },
          success:function(json){
            $(".card-body").html("");
            $(".card-title").html('Company');

            $(".card-body").html(json.html_form);
            $(".card-title").html(json.cus_name_th);
            $("#id_cus_id_error").html('');
            $("#id_cus_brn_error").html('');
            $("#id_cus_vol_error").html('');

            if (json.errorlist) {     
              for (item in json.errorlist) {
                switch(item) {
                  case 'cus_id':
                    if(json.errorlist.cus_id)
                      $("#id_cus_id_error").html(json.errorlist.cus_id);
                    break;
                  case 'cus_brn':
                    if(json.errorlist.cus_brn)
                      $("#id_cus_brn_error").html(json.errorlist.cus_brn);
                    break;
                  case 'cus_vol':
                    if(json.errorlist.cus_vol)
                      $("#id_cus_vol_error").html(json.errorlist.cus_vol);
                    break;
                }
              }
            }
          },
          error : function(xhr,errmsg,err) {
          console.log(xhr.status + ": " + xhr.responseText);
      }
    });

  });

</script>

{% endblock %}

contract/templates/contract/generate_contract.html
{% extends "page_generic_print.html" %}

{% load i18n %}
{% load humanize %}
{% block title %} Download Contract {% endblock %}
{% load static %}
{% load widget_tweaks %}

{% block content %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-8">
            {% if language_option == 'T' %}
            <strong><h4 class="m-0 pt-2 text-dark">{{ cnt_id}} - {{customer.cus_name_th}}</h4></strong>
            {% else %}
            <strong><h4 class="m-0 pt-2 text-dark">{{ cnt_id}} - {{customer.cus_name_en}}</h4></strong>
            {% endif %}
          </div>
          <div class="col-sm-4 pt-2">
            <div class="float-right">
              <button type="button" class="btn btn-default btn-sm" onclick="closetab()">&nbsp;&nbsp;{% trans 'Close' %}&nbsp;&nbsp;</button>              
              &nbsp;&nbsp;|&nbsp;&nbsp;
              <a type="button" class="btn btn-info btn-sm" href="{% url 'download-contract' docx_file_name %}"><i class="fas fa-download"></i>&nbsp;&nbsp;{% trans 'Download file' %}</a>

              <a href="{% url 'print-contract' pdf_file_name %}" target="_blank" class="btn btn-primary btn-sm"><i class="fas fa-print"></i> Print</a>
              <!--<a href="javascript:void(0);" id="id_print_contract" class="btn btn-primary btn-sm"><i class="fas fa-print"></i> Print</a>-->

            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div id="contract_list" class="card">

        <div class="card-body">

          {% if language_option == 'T' %}
            {% if is_new_report == '1' %}
              {% if is_amendment == '1' %}
                <!-- Guarding Services Addendum -->
                {% include 'contract/reports/renc102a_th.html' %}                
              {% else %}
                <!-- Guarding Services -->
                {% include 'contract/reports/renc102_th.html' %}
              {% endif %}
            {% else %}
              {% if is_amendment == '1' %}
                <!-- Service Agreement Amendment -->
                {% include 'contract/reports/rec102a_th.html' %}
              {% else %}
                <!-- Service Agreement -->
                {% include 'contract/reports/rec102_th.html' %}
              {% endif %}
            {% endif %}
          {% else %}
            {% if is_new_report == '1' %}
              {% if is_amendment == '1' %}
                <!-- GUARDING SERVICES ADDENDUM -->                
                {% include 'contract/reports/renc102a_en.html' %}
              {% else %}
                <!-- GUARDING SERVICES -->
                {% include 'contract/reports/renc102_en.html' %}
              {% endif %}
            {% else %}
              {% if is_amendment == '1' %}
              <!-- SERVICE AGREEMENT AMENDMENT -->
                {% include 'contract/reports/rec102a_en.html' %}
              {% else %}
                <!-- SERVICE AGREEMENT -->
                {% include 'contract/reports/rec102_en.html' %}
              {% endif %}
            {% endif %}
          {% endif %}        
        </div>        

      </div>
    </section>

  </div>
{% endblock %}

{% block javascript %}
<script>
  function closetab() {
    window.top.close();  
  }

  $("#id_print_contract").on('click', function(){

    /*
    var css = '@page { size: portrait; margin: 5mm 5mm 5mm 5mm; }',
        head = document.head || document.getElementsByTagName('head')[0],
        style = document.createElement('style');

    style.type = 'text/css';
    style.media = 'print';

    if (style.styleSheet){
      style.styleSheet.cssText = css;
    } else {
      style.appendChild(document.createTextNode(css));
    }

    head.appendChild(style);
    */


    window.print();
    //onClick="javascript:window.print();" 
  });
</script>

{% endblock %}

contract/templates/contract/partial_contract_list.html
{% for item in current_page %}
    <tr>
        <td>{{item.cnt_id}}</td>
        <td><a href="{% url 'contract-update' item.cnt_id %}">{{item.cus_name_th}}</a></td>
        <td>{{item.cus_name_en}}</td>

        {% comment %}
        <td>
          {% if item.cnt_active %}
          <span class="badge badge-success">Active</span>
          {%else%}
          <span class="badge badge-secondary">Pending</span>
          {%endif%}
        </td>
        {% endcomment %}
        <td class="text-right py-0 align-middle">
          <div class="btn-group btn-group-sm">
            <a href="{% url 'contract-update' item.cnt_id %}" type="button" class="btn btn-info btn-xs js-update-customer" data-url="{% url 'contract-update' item.cnt_id %}">
              <i class="fas fa-pen fa-xs"></i>
            </a>
            &nbsp;
            <button type="button" onclick="delete_customer_contract('{{item.cnt_id}}')" class="btn btn-danger btn-xs js-delete-contract"><i class="fas fa-trash fa-xs"></i></button>

          </div>
        </td>                    
    </tr>
{% endfor %}